export const STUDENT_RESPONSE_EXAMPLE = {
  studentRegistration: '202301',
  title: 'Sistema de Gerenciamento de TCC com Blockchain',
  defenseDate: '2024-01-05T10:00:00.000Z',
  location: 'Sala 301 - Prédio da Computação',
  finalGrade: 8.5,
  result: 'APPROVED',
  reason: '',
  registeredBy: 'coordinator@ifal.local',
  defenseStatus: 'COMPLETED',
  advisor: {
    id: 'advisor-uuid-123',
    name: 'Prof. Dr. João Silva',
    email: 'joao.silva@ifal.local',
    specialization: 'Engenharia de Software',
    isActive: true,
  },
  examBoard: [
    {
      name: 'Prof. Dr. Carlos Alberto Silva',
      email: 'carlos.silva@ifal.local',
    },
    {
      name: 'Profa. Dra. Maria Fernanda Costa',
      email: 'maria.costa@ifal.local',
    },
    {
      name: 'Prof. Dr. João Pedro Santos',
      email: 'joao.santos@ifal.local',
    },
  ],
  coStudents: [
    {
      id: 'student-uuid-789',
      registration: '00678901',
      name: 'Beatriz Lima Souza',
      email: 'aluno6@ufrgs.edu.br',
    },
  ],
  signatures: [
    {
      role: 'coordinator',
      email: 'coordinator@ifal.local',
      timestamp: '2024-01-05T10:30:00.000Z',
      status: 'APPROVED',
    },
    {
      role: 'advisor',
      email: 'advisor@ifal.local',
      timestamp: '2024-01-05T10:15:00.000Z',
      status: 'REJECTED',
      justification: 'Document does not meet minimum formatting requirements',
    },
    {
      role: 'student',
      email: 'student@ifal.local',
      timestamp: '2024-01-05T10:05:00.000Z',
      status: 'APPROVED',
    },
  ],
  validatedAt: '2024-01-05T10:30:00.000Z',
  documents: [
    {
      id: 'doc-uuid-v2',
      version: 2,
      status: 'APPROVED',
      changeReason: 'Correção de nota final após revisão',
      documentCid: 'QmX1234567890abcdefghijklmnop',
      blockchainTxId: 'tx_abc123def456',
      blockchainRegisteredAt: '2024-01-05T10:30:00.000Z',
      createdAt: '2024-01-05T10:00:00.000Z',
      downloadUrl: '/api/documents/doc-uuid-v2/download',
    },
    {
      id: 'doc-uuid-v1',
      version: 1,
      status: 'INACTIVE',
      changeReason: undefined,
      documentCid: 'QmY9876543210zyxwvutsrqponml',
      blockchainTxId: 'tx_xyz789ghi012',
      blockchainRegisteredAt: '2024-01-04T15:00:00.000Z',
      createdAt: '2024-01-04T14:30:00.000Z',
      downloadUrl: '/api/documents/doc-uuid-v1/download',
    },
  ],
};
