export enum NotificationContextType {
  DEFENSE_APPROVAL = 'DEFENSE_APPROVAL',
  DOCUMENT_APPROVAL = 'DOCUMENT_APPROVAL',
  DEFENSE_CREATED = 'DEFENSE_CREATED',
  DEFENSE_RESULT = 'DEFENSE_RESULT',
  GENERAL = 'GENERAL',
}
