export enum EmailTemplate {
  DEFENSE_SCHEDULED_ADVISOR = 'DEFENSE_SCHEDULED_ADVISOR',
  DEFENSE_SCHEDULED_STUDENT = 'DEFENSE_SCHEDULED_STUDENT',
  DEFENSE_RESULT_STUDENT = 'DEFENSE_RESULT_STUDENT',
  DEFENSE_RESULT_ADVISOR = 'DEFENSE_RESULT_ADVISOR',
  DOCUMENT_APPROVAL_REQUEST = 'DOCUMENT_APPROVAL_REQUEST',
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED',
}
