export enum EmailTemplate {
  DEFENSE_SCHEDULED = 'DEFENSE_SCHEDULED',
  DEFENSE_CANCELED = 'DEFENSE_CANCELED',
  DEFENSE_RESCHEDULED = 'DEFENSE_RESCHEDULED',
  DEFENSE_RESULT = 'DEFENSE_RESULT',
  DOCUMENT_APPROVAL_REQUEST = 'DOCUMENT_APPROVAL_REQUEST',
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED',
}
